### ISSUE TITLE
"Clear Task Color" does not clear task color unless the app is restarted

### ISSUE THREAD

**Issue by ryonakano** [lainsce/timetable#10]
![peek 2018-10-23 21-34](https://user-images.githubusercontent.com/26003928/47360916-9ccb9580-d70b-11e8-9100-9508c07c24ae.gif)

"Clear Task Color" does not clear the task color immediately, while changing to other colors does immediately. And instead, the button color changes from white to gray. And I get this error message:

```
** (com.github.lainsce.timetable:702): WARNING **: 21:34:26.587: TaskBox.vala:655: Failed to parse css style : <data>:7:47'' is not a valid color name
```

After quitting and re-oping the app, the color of the task is removed successfully.

With Timetable 1.0.3, on Juno

**Comment by lainsce** [comment]
It's fixed in master, a new release will fix this.

**Comment by ryonakano** [comment]
Wow, thank you!!
