### ISSUE TITLE
Allow drag&drop of tasks between days

### ISSUE THREAD

**Issue by megatux** [lainsce/timetable#15]
Because it's so common to reorganize them

**Comment by lainsce** [comment]
I'll see what I can do!

**Comment by Philip-Scott** [comment]
Would be nice if you could move them up and down as well :)

**Comment by megatux** [comment]
Maybe :thinking: .They could be sorted by start-time, I guess, but  when we mix all-day task with a tohers with a period it could be hard to tell the order

**Comment by lainsce** [comment]
Now tasks are sorted by start time, with All-Day tasks at the top.

Now to go and implement drag 'n' drop.

**Comment by lainsce** [comment]
Leaving here a request for help on implementing this.

**Comment by lainsce** [comment]
Thinking about this further, it doesn't make sense to reorganize when the app already organizes the tasks by starting time automatically. If the user needs to change a task's order they could simply just change that task's start time.
