### ISSUE TITLE
Label size is too small

### ISSUE THREAD

**Issue by Philip-Scott** [lainsce/timetable#21]
Looks like the gear and the trash icon are a bit too big on the space in the app, specially if you make it so that it also includes Sat/Sunday. A way to do it could be making both the gear and trash vertically, or even hiding them when not focused 

![image](https://user-images.githubusercontent.com/10786508/47822897-8f299780-dd2b-11e8-9144-db7a4d04b4ec.png)

**Comment by lainsce** [comment]
I'll see about hiding unless focused. :smile:

**Comment by lainsce** [comment]
Fixed in master!
