### ISSUE TITLE
Add time slot progress indicator

### ISSUE THREAD

**Issue by SubhadeepJasu** [lainsce/timetable#25]
Version 1.0.3
Show the progress in a particular time slot as time moves on. May be a progress bar, or a darker/lighter shade in the background of the Task widgets.
This brings in to account urgency and a general ease of looking up time and understanding how much time is left, etc.
Thanks!

**Comment by lainsce** [comment]
I'll see how to do this.

**Comment by lainsce** [comment]
After much design mockupping and coding and trying to fit this idea on the tasks in a meaningful way, I found no good way to show this to the user without making the app feel unresponsive due to tracking each tasks time. Sorry but this is not possible to feasibly do.
