### ISSUE TITLE
Add ability to scroll the task panes, without affecting the size of the app

### ISSUE THREAD

**Issue by SubhadeepJasu** [lainsce/timetable#26]
Version 1.0.3
Moving the Tasks in to the Gtk Scrollable, would allow seemingly unlimited tasks to be added to each column.
Thanks!

**Comment by SubhadeepJasu** [comment]
One of the main reasons for this is to have more fragmented time-slots, this helps off loading, long strenuous jobs. I would also like to follow standard time management techniques like Kaizen, which requires many fragmented small time slots of work and free-time and variation. This is not possible in the current state of the app as of v1.0.3

**Comment by lainsce** [comment]
Each day column is scrollable by default, shouldn't be a bug. Just open your tasks as you would and they'll appear sorted by time, even if the time chunk is small like in Kaizen. Closing issue.
