### ISSUE TITLE
Prevent unintended rearranging

### ISSUE THREAD

**Issue by SubhadeepJasu** [lainsce/timetable#27]
Version 1.0.3
The app automatically rearranged the table in an unintended manner. Unable to reproduce the same issue, which makes me think, its a bug.

Thanks!

**Comment by lainsce** [comment]
It rearranges based on time of the task, it's not a bug.

**Comment by SubhadeepJasu** [comment]
I see. I had a slot right after 12o'clock at night and it was rearranged to the beginning of the day. So I thought it was a bug. Settings the starting time to 23:59 fixed it. I see now. Its actually a great feature, sorry for the issue.
