### ISSUE TITLE
How we load the current saved Timetables?

### ISSUE THREAD

**Issue by alex285** [lainsce/timetable#32]
we can save time tables, but how we load them? when i open the app i don't find a way to see my already saved timetables. do i miss something? :/

**Comment by ryonakano** [comment]
Duplication of #24?

**Comment by alex285** [comment]
hello @ryonakano 
i already saw that, but it isn't duplication b/c i dont want to import from lets say other apps, i want only to be able to see the timetables i have created within this app

for example something like a sidebar with timetables

**Comment by lainsce** [comment]
Maybe it's best if the app has a "Open..." button on the headerbar which opens older timetables instead of a sidebar.

**Comment by alex285** [comment]
> Maybe it's best if the app has a "Open..." button on the headerbar which opens older timetables instead of a sidebar.

hello @lainsce! i dont think that would really solved the problem. what someone wants to have on such app, is all their timetables easily accessible when they start the app, without needing to "Open" anything

shouldn't necessarily be a sidebar. it could be another view, with just timetables, and when you click on one you get inside timetable view

**Comment by lainsce** [comment]
I'll see how to best approach this.

**Comment by lainsce** [comment]
This is getting worked on in the branch wip-dev!
