### ISSUE TITLE
Push on Flathub; is #32 a blocker?

### ISSUE THREAD

**Issue by alex285** [lainsce/timetable#33]
i'd like to push on Flathub, but i think it would be better to do after https://github.com/lainsce/timetable/issues/32 is resolved. It is an essential feature, and without it, maybe someone installs the app, won't find it convenient to use, un-install it, and never install/try it again, even if this feature has been fixed

**Comment by lainsce** [comment]
I think #32 isn't a blocker for an initial release; a new flatpak can be done when it is fixed, right?

**Comment by alex285** [comment]
@lainsce please also check the patch https://github.com/flathub/flathub/pull/773. if forces elementary theme, b/c in GNOME it breaks visuals with other themes

**Comment by lainsce** [comment]
That's something similar to what I did in Notejot.

**Comment by alex285** [comment]
hey @lainsce you wanna work on port from FileChooser to GTKNative, b/c @bilelmoussaoui doesn't like the `--host` access. i think i can do it, but i believe my patches will be bad, and you will lose more time to review them, than doing it your self!

But whatever you want, i don't really mind to try some Vala for once :)

**Comment by lainsce** [comment]
Try doing it, if it becomes bad I can fix it later

**Comment by lainsce** [comment]
Since theere's a flatpak submission in FlatHub now, this issue isn't needed. If one needs to follow-up, please do so in Issue #32.
