### ISSUE TITLE
Task times should reflect system 12h/24h time setting.

### ISSUE THREAD

**Issue by ChristopherNugent** [lainsce/timetable#35]
The app seems to use 24 hour time regardless of the user's system setting.

![image](https://user-images.githubusercontent.com/21992673/50935032-78847880-141f-11e9-8acb-c65691f17c82.png)

**Comment by lainsce** [comment]
This is by design so the task representation takes as little horizontal space as possible for those with challenged monitor sizes to enjoy my app as well :heart:
