### ISSUE TITLE
[Feature Request] Proper Timeslots

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/timetable#36]
It would be nice is the app could have proper timeslots, seperating the columns in hourly rows and sorting the open tasks to the appropriate timeslot automatically. This way it would be way more intuitive to read when which task is supposed to be done, as the relative position reveals that information. Similar to how calendars do it.

**Comment by lainsce** [comment]
In `master`, or by building it from this repository, you now have icons beside the week columns with icons showing the order of tasks. I just need to fix the other bug (#32) before pushing to AppCenter.
