### ISSUE TITLE
[BUG] Show weekends button doesn't save the state of this option.

### ISSUE THREAD

**Issue by gquittet** [lainsce/timetable#41]
![image](https://user-images.githubusercontent.com/11082739/54056450-642ae500-41f0-11e9-8330-a6c67346129d.png)

This screenshot and this title recap this problem.

**Comment by lainsce** [comment]
I'll see what I can do. Stay tuned for a fix.

**Comment by lainsce** [comment]
Fixed.

**Comment by gquittet** [comment]
Great job! :+1:
