### ISSUE TITLE
Add ability to change day

### ISSUE THREAD

**Issue by RavetcoFX** [lainsce/timetable#46]
It would be nice for a setting to change the day, either with the setting pop over, or by dragging and dropping

**Comment by lainsce** [comment]
This was being coded already, I'll resume work on this by August.

**Comment by RavetcoFX** [comment]
Thanks for the reply

**Comment by brcmesquita** [comment]
Yeah! Drag n' drop!

**Comment by lainsce** [comment]
Duplicating items could be resolved with this:

In the task edit popup, a Day chooser grid of buttons. Which would mean that the individual buttons on each column to add tasks would be unified and put on the toolbar instead.

**Comment by lainsce** [comment]
Implementing drag and drop

Might take a while.

**Comment by lainsce** [comment]
FIXED :tada: :tada:
