### ISSUE TITLE
Add ability to duplicate itens

### ISSUE THREAD

**Issue by brcmesquita** [lainsce/timetable#47]
Hello!
I am very interested in using TimeTable. I have some tasks during the week that are repeated (like reading emails, attending classes, writing etc). I would like you to add the possibility of duplicating the items already created.

**Comment by lainsce** [comment]
This could be done in one step with #46 as well.

**Comment by brcmesquita** [comment]
Thx for the reply!

**Comment by Akzel94** [comment]
I'm not sure I understand why this was closed. If it's possible to duplicate items now, the way to do so isn't obvious.

**Comment by JJBordy** [comment]
I guess the only way to copy tasks is to open the .org file with a text editor, and copy/paste them easily :)
