### ISSUE TITLE
Don't save changes

### ISSUE THREAD

**Issue by garbunus** [lainsce/timetable#49]
Hi, congratulations for your app.
about bug:  after put a new activity, on edit this, don't save any changes.

**Comment by lainsce** [comment]
Hi, could you elaborate a bit more? The app always should save any changes, and even pop a dialog saying there's changes if you push New button.

**Comment by lainsce** [comment]
Please help me understand. If you do not give me information, I cannot help you with the bug you are facing.

**Comment by lainsce** [comment]
Fixed what should be your problem, I think.

**Comment by garbunus** [comment]
Hi, sorry about my delay. Busy days.
This is what happening:

![timetable_bug](https://user-images.githubusercontent.com/28625502/62971451-eba00400-bddf-11e9-8e65-424f9e04fc67.gif)

Best

**Comment by lainsce** [comment]
The newest release due for AppCenter hopefully this Friday should help with it :heart:

**Comment by garbunus** [comment]
> The newest release due for AppCenter hopefully this Friday should help with it

Thank you so much
