### ISSUE TITLE
Problem with resizing

### ISSUE THREAD

**Issue by alainm23** [lainsce/timetable#7]
Your application looks amazing, but it's too big to use on my monitor (1366 * 768), if you could fix this please, thank you very much ...
![captura](https://user-images.githubusercontent.com/33765137/47022998-50d58b00-d124-11e8-8aef-723ef9d8824a.png)

**Comment by lainsce** [comment]
I'll fix this in the next version

**Comment by lainsce** [comment]
Fixed.
