### ISSUE TITLE
Make Day Columns background colour dark for Dark Theme users

### ISSUE THREAD

**Issue by terndrup** [lainsce/timetable#9]
This app is great but I have one stylesheet suggested which relates to users of the native Dark elementary OS Juno theme.

If we can change the dark stylesheet to make the "Day column backgounds" dark as well, as the light grey current colour is not ideal and makes the Dark theme look broken.

See screenshot:

![Broken dark theme](https://i.imgur.com/HWkTgK2.png)

I can fix this myself in the near future but just wanted to raise it for now.

**Comment by lainsce** [comment]
This is fixed in master, a new release will have it.

**Comment by terndrup** [comment]
Great! Assuming that includes the buttons, headers and any other minor inconsistencies?
